# Generated by Django 3.2.18 on 2023-02-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
